CREATE TABLE IF NOT EXISTS public.game_requests
(
    game_request_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    player_id integer NOT NULL,
    date_created varchar(32) NOT NULL,
    time_control integer NOT NULL,
    PRIMARY KEY (game_request_id),
    CONSTRAINT "game_request_id_UNIQUE" UNIQUE (game_request_id),
    CONSTRAINT "game_requests.player_id" FOREIGN KEY (player_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
        NOT VALID,
    CONSTRAINT "game_requests.time_control" FOREIGN KEY (time_control)
        REFERENCES public.time_controls (time_control_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

ALTER TABLE IF EXISTS public.game_requests
    OWNER to postgres;