CREATE TABLE IF NOT EXISTS public.games
(
    game_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    black_player integer NOT NULL,
    white_player integer NOT NULL,
    date_started varchar(32) NOT NULL,
    result integer NOT NULL DEFAULT 0,
    completed boolean NOT NULL DEFAULT false,
    time_control integer NOT NULL,
    fen varchar(256) NOT NULL,
    pgn text NOT NULL,
    player_turn integer NOT NULL,
    clock_white integer NOT NULL DEFAULT 0,
    clock_black integer NOT NULL DEFAULT 0,
    max_clock integer NOT NULL,
    last_tick_white bigint,
    last_tick_black bigint,
    draw_offer integer,
    white_end_elo integer,
    black_end_elo integer,
    PRIMARY KEY (game_id),
    CONSTRAINT "game_id_UNIQUE" UNIQUE (game_id),
    CONSTRAINT "games.black_player" FOREIGN KEY (black_player)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
        NOT VALID,
    CONSTRAINT "games.white_player" FOREIGN KEY (white_player)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
        NOT VALID,
    CONSTRAINT "games.time_control" FOREIGN KEY (time_control)
        REFERENCES public.time_controls (time_control_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "games.draw_offer" FOREIGN KEY (draw_offer)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
        NOT VALID
);

ALTER TABLE IF EXISTS games
    OWNER to postgres;
	
GRANT ALL ON TABLE games TO postgres;