CREATE TABLE IF NOT EXISTS previous_positions
(
    previous_position_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    game_id integer NOT NULL,
    fen varchar(256) NOT NULL,
    PRIMARY KEY (previous_position_id),
    CONSTRAINT "previous_position_id_UNIQUE" UNIQUE (previous_position_id),
    CONSTRAINT "previous_positions.game_id" FOREIGN KEY (game_id)
        REFERENCES public.games (game_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
        NOT VALID
);

ALTER TABLE IF EXISTS previous_positions
    OWNER to postgres;
	
GRANT ALL ON TABLE previous_positions TO postgres;