CREATE TABLE IF NOT EXISTS time_controls
(
    time_control_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "time" integer NOT NULL,
    time_unit varchar(16) NOT NULL,
    increment integer NOT NULL,
    increment_unit varchar(16) NOT NULL,
    PRIMARY KEY (time_control_id),
    CONSTRAINT "time_control_id_UNIQUE" UNIQUE (time_control_id)
);

ALTER TABLE IF EXISTS time_controls
    OWNER to postgres;
	
GRANT ALL ON TABLE time_controls TO postgres;